service: brain-cache
custom:
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  httpApi:
    cors: true
  environment:
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USERNAME: ${self:custom.secrets.DB_USERNAME}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
functions:
  findPage:
    handler: handler.findPage
    name: ${self:service}-findPage
    events:
      - http:
          path: pages/search
          method: get
          cors: true
  star:
    handler: handler.star
    name: ${self:service}-star
    events:
      - http:
          path: star
          method: post
          cors: true
  unstar:
    handler: handler.unstar
    name: ${self:service}-unstar
    events:
      - http:
          path: unstar
          method: delete
          cors: true
  highlight:
    handler: handler.highlight
    name: ${self:service}-highlight
    events:
      - http:
          path: pages/{id}/highlight
          method: post
          cors: true
  unhighlight:
    handler: handler.unhighlight
    name: ${self:service}-unhighlight
    events:
      - http:
          path: pages/{id}/unhighlight
          method: post
          cors: true
  search:
    handler: handler.search
    name: ${self:service}-search
    events:
      - http:
          path: search
          method: post
          cors: true
